# BASICS

## Python List - to - Numpy Array

In [1]:
import numpy as np  # import the NumPy library
arr = np.array([-1, 2, 5], dtype=np.float32)

arr2d = np.array([[0, 1, 2], [3, 4, 5]],
               dtype=np.float32)

print(repr(arr))
print(repr(arr2d))

array([-1.,  2.,  5.], dtype=float32)
array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)


* When there are heterogenous elements, all the element will be upcast to the highest level type.

In [2]:
arr = np.array([0, 0.1, 2])
print(repr(arr))

array([0. , 0.1, 2. ])


## Copying Numpy Arrays

In [3]:
b = np.array([9, 8])
d = b.copy()

print('Array b: {}'.format(repr(b)))
b[1] = 11
print('Array b: {}'.format(repr(b)))
print('Array d: {}'.format(repr(d)))

Array b: array([9, 8])
Array b: array([ 9, 11])
Array d: array([9, 8])


## Type Casting

In [4]:
arr = np.array([0, 1, 2])
print(arr.dtype)

# Explicit Typecasting
arr = arr.astype(np.float32)
print(arr.dtype)

int64
float32


## NaN

In [5]:
arr = np.array([np.nan, 1, 2])
print(repr(arr))

array([nan,  1.,  2.])


* np.nan cannot take on an integer type.

In [6]:
# Will result in a ValueError
np.array([np.nan, 1, 2], dtype=np.int32)

ValueError: cannot convert float NaN to integer

## Infinity

In [ ]:
print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 1])
print(repr(arr))

 * np.inf cannot take on an integer type.

In [ ]:
# Will result in an OverflowError
np.array([np.inf, 3], dtype=np.int32)

## Ranged Data

* arange
* linspace

In [ ]:
arr = np.arange(5)
print(repr(arr))

arr = np.arange(5.1)
print(repr(arr))

arr = np.arange(-1, 4)
print(repr(arr))

arr = np.arange(-1.5, 4, 2)
print(repr(arr))

In [ ]:
arr = np.linspace(5, 11, num=4) # Linspace Includes End
print(repr(arr))

points = np.linspace(-3.5, 1.5, num = 101)
print(repr(points))

arr = np.linspace(5, 11, num=4, endpoint=False) # Linspace Includes End = Unless endpoint set to False
print(repr(arr))

arr = np.linspace(5, 11, num=4, dtype=np.int32) # Linspace can take dtype
print(repr(arr))

## Reshaping Data

* It takes in an array and a new shape as required arguments. The new shape must exactly contain all the elements from the input array.
* For example, we could reshape an array with 12 elements to (4, 3), but we can't reshape it to (4, 4).
* We are allowed to use the special value of -1 in at most one dimension of the new shape. The dimension with -1 will take on the value necessary to allow the new shape to contain all the elements of the array.

In [ ]:
arr = np.arange(8)

reshaped_arr = np.reshape(arr, (2, 4))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

reshaped_arr = np.reshape(arr, (-1, 2, 2))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

## Flatten

In [ ]:
arr = np.arange(8)
arr = np.reshape(arr, (2, 4))
flattened = arr.flatten()
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(flattened))
print('flattened shape: {}'.format(flattened.shape))

## Transposing

In [ ]:
arr = np.arange(8)
arr = np.reshape(arr, (4, 2))
transposed = np.transpose(arr)
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(transposed))
print('transposed shape: {}'.format(transposed.shape))

In [ ]:
arr = np.arange(24)
print(repr(arr))
arr = np.reshape(arr, (3, 4, 2))
print(repr(arr))
transposed = np.transpose(arr, axes=(1, 2, 0)) # To specify where the switching happens
print(repr(transposed))
print('arr shape: {}'.format(arr.shape))
print('transposed shape: {}'.format(transposed.shape))

## Zeroes and Ones

In [ ]:
arr = np.zeros(4)
print(repr(arr))

arr = np.ones((2, 3))
print(repr(arr))

arr = np.ones((2, 3), dtype=np.int32)
print(repr(arr))

ones_arr = np.ones_like(transposed)
print(repr(ones_arr))

# MATHEMATICS

## Arithemetic

In [ ]:
arr = np.array([[1, 2], [3, 4]])

# Add 1 to element values
print(repr(arr + 1))

# Subtract element values by 1.2
print(repr(arr - 1.2))

# Double element values
print(repr(arr * 2))

# Halve element values
print(repr(arr / 2))

# Integer division (half)
print(repr(arr // 2))

# Square element values
print(repr(arr**2))

# Square root element values
print(repr(arr**0.5))

In [ ]:
def f2c(temps):
  return (5/9)*(temps-32)

fahrenheits = np.array([32, -4, 14, -40])
celsius = f2c(fahrenheits)
print('Celsius: {}'.format(repr(celsius)))

## Non-linear Functions

In [ ]:
arr = np.array([[1, 2], [3, 4]])

# Raised to power of e
print(repr(np.exp(arr)))

# Raised to power of 2
print(repr(np.exp2(arr)))

arr2 = np.array([[1, 10], [np.e, np.pi]])

# Natural logarithm
print(repr(np.log(arr2)))

# Base 10 logarithm
print(repr(np.log10(arr2)))

In [ ]:
arr = np.array([[1, 2], [3, 4]])

# Raise 3 to power of each number in arr
print(repr(np.power(3, arr)))

arr2 = np.array([[10.2, 4], [3, 5]])

# Raise arr2 to power of each number in arr
print(repr(np.power(arr2, arr)))

## Matrix Multiplication

In [ ]:
# Required condition = (m x n) * (n x k) - results in (m, k) dimensions

arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])

print(np.matmul(arr1, arr2)) # Multiplying 1D & 1D results in dot product

arr3 = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])

arr4 = np.array([[-1, 0, 1], 
                 [3, 2, -4]])

print(repr(np.matmul(arr3, arr4)))
print(repr(np.matmul(arr4, arr3)))

# This will result in ValueError
print(repr(np.matmul(arr3, arr3)))

# RANDOM

## Generate Random

In [ ]:
# Random integer is chosen uniformly from the range [0, n).
print(np.random.randint(5))
print(np.random.randint(5))

# Random integer is chosen uniformly from the range [5, 6).
print(np.random.randint(5, high=6))

# Multi dimensonal
random_arr = np.random.randint(-3, high=14,size=(2, 5, 3))
print(repr(random_arr))

## Generate Random with Seed

In [ ]:
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

# New seed
np.random.seed(2)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

# Original seed
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

## Shuffle

In [ ]:
vec = np.array([1, 2, 3, 4, 5])
np.random.shuffle(vec)
print(repr(vec))
np.random.shuffle(vec)
print(repr(vec))

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
np.random.shuffle(matrix)
print(repr(matrix))

## Random from Distribution

* __Uniform Distribution__

In [ ]:
print(np.random.uniform()) # Default [0.0, 1.0)
print(np.random.uniform(low=-1.5, high=2.2))
print(repr(np.random.uniform(size=3)))
print(repr(np.random.uniform(low=-3.4, high=5.9,
                             size=(2, 2))))

* __Gaussian / Normal Distribution__

In [ ]:
print(np.random.normal())
# loc = mean, scale = standard deviation
print(np.random.normal(loc=1.5, scale=3.5))
print(repr(np.random.normal(loc=-2.4, scale=4.0,
                            size=(2, 2))))

* __Custom Distribution__

In [ ]:
colors = ['red', 'blue', 'green']
print(np.random.choice(colors))
print(repr(np.random.choice(colors, size=2)))
print(repr(np.random.choice(colors, size=(2, 2),
                            p=[0.8, 0.19, 0.01])))

# INDEXING

## Accessing

In [7]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[4])

arr = np.array([[6, 3], [0, 2]])
# Subarray
print(repr(arr[0]))

1
5
array([6, 3])


## Slicing

In [8]:
arr = np.array([1, 2, 3, 4, 5])
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[2:4]))
print(repr(arr[:-1]))
print(repr(arr[-2:]))

array([1, 2, 3, 4, 5])
array([2, 3, 4, 5])
array([3, 4])
array([1, 2, 3, 4])
array([4, 5])


In [9]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[:, -1]))
print(repr(arr[:, 1:]))
print(repr(arr[0:1, 1:]))
print(repr(arr[0, 1:]))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
array([[4, 5, 6],
       [7, 8, 9]])
array([3, 6, 9])
array([[2, 3],
       [5, 6],
       [8, 9]])
array([[2, 3]])
array([2, 3])


## Argmin & Argmax

In [10]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])
print(np.argmin(arr[0]))
print(np.argmax(arr[2]))
print(np.argmin(arr))

2
1
5


In [13]:
# Using axis=0 meant the function found the index of 
# the minimum row element for each column. 

arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])
print(repr(np.argmin(arr, axis=0)))

# When we used axis=1, the function found the index of 
# the minimum column element for each row.

print(repr(np.argmin(arr, axis=1)))
print(repr(np.argmax(arr, axis=-1)))

array([2, 0, 1])
array([2, 2, 0])
array([1, 1, 1])


# FILTERING

__Get Boolean Array__

In [15]:
arr = np.array([[0, 2, 3],
                [1, 3, -6],
                [-3, -2, 1]])

print(repr(arr == 3))
print(repr(arr > 0))
print(repr(arr != 1))

# Negated from the previous step
print(repr(~(arr != 1)))

array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])
array([[False,  True,  True],
       [ True,  True, False],
       [False, False,  True]])
array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True, False]])
array([[False, False, False],
       [ True, False, False],
       [False, False,  True]])


__NAN__

In [16]:
arr = np.array([[0, 2, np.nan],
                [1, np.nan, -6],
                [np.nan, -2, 1]])
print(repr(np.isnan(arr)))

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False]])


__Where__

In [19]:
print(repr(np.where([True, False, True])))

arr = np.array([0, 3, 5, 3, 1])
print(repr(np.where(arr == 3)))

arr = np.array([[0, 2, 3],
                [1, 0, 0],
                [-3, 0, 0]])

x_ind, y_ind = np.where(arr != 0)

print(repr(x_ind)) # x indices of non-zero elements
print(repr(y_ind)) # y indices of non-zero elements
print(repr(arr[x_ind, y_ind]))

(array([0, 2]),)
(array([1, 3]),)
array([0, 0, 1, 2])
array([1, 2, 0, 0])
array([ 2,  3,  1, -3])


__Multi Arg Where__

In [23]:
np_filter = np.array([[True, False], 
                      [False, True]])

positives = np.array([[1, 2], 
                      [3, 4]])

negatives = np.array([[-2, -5], 
                      [-1, -8]])

print(repr(np.where(np_filter, positives, negatives)))

np_filter = positives > 2
print(repr(np.where(np_filter, positives, negatives)))

np_filter = negatives > 0
print(repr(np.where(np_filter, positives, negatives)))

array([[ 1, -5],
       [-1,  4]])
array([[-2, -5],
       [ 3,  4]])
array([[-2, -5],
       [-1, -8]])


__Replace with Constant Upon Unsatisfied Condition__

In [24]:
np_filter = np.array([[True, False], [False, True]])
positives = np.array([[1, 2], [3, 4]])
print(repr(np.where(np_filter, positives, -1)))

array([[ 1, -1],
       [-1,  4]])


__Conditional / Any / All__

In [29]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [3, 9, 1]])
print(repr(arr > 0))
print(np.any(arr > 0))
print(np.all(arr > 0))

print(repr(np.any(arr > 0, axis=0))) # Col
print(repr(np.any(arr > 0, axis=1))) # Row
print(repr(np.all(arr > 0, axis=1))) # Row

array([[False, False, False],
       [ True,  True, False],
       [ True,  True,  True]])
True
False
array([ True,  True,  True])
array([False,  True,  True])
array([False, False,  True])


In [31]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [3, 9, 1]])
has_positive = np.any(arr > 0, axis=1) # Col
print(has_positive)
print(repr(arr[np.where(has_positive)]))

[False  True  True]
array([[ 4,  5, -6],
       [ 3,  9,  1]])


# STATISTICS
https://numpy.org/doc/stable/reference/routines.statistics.html

## Analysis

In [35]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(arr.min())
print(arr.max())

print(repr(arr.min(axis=0)))
print(repr(arr.max(axis=-1)))

-60
72
array([ -3,  -2, -60])
array([72,  3,  4])


## Statistical Metrics

In [36]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(np.mean(arr)) # Mean
print(np.var(arr)) # Variance
print(np.median(arr)) # Median
print(repr(np.median(arr, axis=-1)))

2.0
977.3333333333334
1.0
array([ 3.,  1., -2.])


# AGGREGATION

## Summation

__Axis wise sum__

In [39]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(np.sum(arr))
print(repr(np.sum(arr, axis=0))) # Col
print(repr(np.sum(arr, axis=1))) # Row

18
array([ -2,  73, -53])
array([ 75, -56,  -1])


__Cumulative Sum__

In [40]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(repr(np.cumsum(arr)))
print(repr(np.cumsum(arr, axis=0)))
print(repr(np.cumsum(arr, axis=1)))

array([ 0, 72, 75, 76, 79, 19, 16, 14, 18])
array([[  0,  72,   3],
       [  1,  75, -57],
       [ -2,  73, -53]])
array([[  0,  72,  75],
       [  1,   4, -56],
       [ -3,  -5,  -1]])


## Concatenation

In [42]:
arr1 = np.array([[0, 72, 3],
                 [1, 3, -60],
                 [-3, -2, 4]])
arr2 = np.array([[-15, 6, 1],
                 [8, 9, -4],
                 [5, -21, 18]])
print(repr(np.concatenate([arr1, arr2])))
print(repr(np.concatenate([arr1, arr2], axis=1)))
print(repr(np.concatenate([arr2, arr1], axis=1)))
print(repr(np.concatenate([arr1, arr2], axis=0)))
print(repr(np.concatenate([arr2, arr1], axis=0)))

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4],
       [-15,   6,   1],
       [  8,   9,  -4],
       [  5, -21,  18]])
array([[  0,  72,   3, -15,   6,   1],
       [  1,   3, -60,   8,   9,  -4],
       [ -3,  -2,   4,   5, -21,  18]])
array([[-15,   6,   1,   0,  72,   3],
       [  8,   9,  -4,   1,   3, -60],
       [  5, -21,  18,  -3,  -2,   4]])
array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4],
       [-15,   6,   1],
       [  8,   9,  -4],
       [  5, -21,  18]])
array([[-15,   6,   1],
       [  8,   9,  -4],
       [  5, -21,  18],
       [  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4]])
