## Python List - to - Numpy Array

In [2]:
import numpy as np  # import the NumPy library
arr = np.array([-1, 2, 5], dtype=np.float32)

arr2d = np.array([[0, 1, 2], [3, 4, 5]],
               dtype=np.float32)

print(repr(arr))
print(repr(arr2d))

array([-1.,  2.,  5.], dtype=float32)
array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)


* When there are heterogenous elements, all the element will be upcast to the highest level type.

In [3]:
arr = np.array([0, 0.1, 2])
print(repr(arr))

array([0. , 0.1, 2. ])


## Copying Numpy Arrays

In [4]:
b = np.array([9, 8])
d = b.copy()

print('Array b: {}'.format(repr(b)))
b[1] = 11
print('Array b: {}'.format(repr(b)))
print('Array d: {}'.format(repr(d)))

Array b: array([9, 8])
Array b: array([ 9, 11])
Array d: array([9, 8])


## Type Casting

In [6]:
arr = np.array([0, 1, 2])
print(arr.dtype)

# Explicit Typecasting
arr = arr.astype(np.float32)
print(arr.dtype)

int64
float32


## NaN

In [7]:
arr = np.array([np.nan, 1, 2])
print(repr(arr))

array([nan,  1.,  2.])


* np.nan cannot take on an integer type.

In [8]:
# Will result in a ValueError
np.array([np.nan, 1, 2], dtype=np.int32)

ValueError: cannot convert float NaN to integer

## Infinity

In [11]:
print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 1])
print(repr(arr))

True
array([inf,  5.])
array([-inf,   1.])


 * np.inf cannot take on an integer type.

In [12]:
# Will result in an OverflowError
np.array([np.inf, 3], dtype=np.int32)

OverflowError: cannot convert float infinity to integer

## Ranged Data

* arange
* linspace

In [13]:
arr = np.arange(5)
print(repr(arr))

arr = np.arange(5.1)
print(repr(arr))

arr = np.arange(-1, 4)
print(repr(arr))

arr = np.arange(-1.5, 4, 2)
print(repr(arr))

array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3])
array([-1.5,  0.5,  2.5])


In [14]:
arr = np.linspace(5, 11, num=4) # Linspace Includes End
print(repr(arr))

arr = np.linspace(5, 11, num=4, endpoint=False) # Linspace Includes End = Unless endpoint set to False
print(repr(arr))

arr = np.linspace(5, 11, num=4, dtype=np.int32) # Linspace can take dtype
print(repr(arr))

array([ 5.,  7.,  9., 11.])
array([5. , 6.5, 8. , 9.5])
array([ 5,  7,  9, 11], dtype=int32)


## Reshaping Data

* It takes in an array and a new shape as required arguments. The new shape must exactly contain all the elements from the input array.
* For example, we could reshape an array with 12 elements to (4, 3), but we can't reshape it to (4, 4).
* We are allowed to use the special value of -1 in at most one dimension of the new shape. The dimension with -1 will take on the value necessary to allow the new shape to contain all the elements of the array.

In [15]:
arr = np.arange(8)

reshaped_arr = np.reshape(arr, (2, 4))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

reshaped_arr = np.reshape(arr, (-1, 2, 2))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
New shape: (2, 4)
array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])
New shape: (2, 2, 2)


## Flatten

In [16]:
arr = np.arange(8)
arr = np.reshape(arr, (2, 4))
flattened = arr.flatten()
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(flattened))
print('flattened shape: {}'.format(flattened.shape))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
arr shape: (2, 4)
array([0, 1, 2, 3, 4, 5, 6, 7])
flattened shape: (8,)


## Transposing